### ISSUE TITLE
POE - Issue in Image View 

### ISSUE THREAD

**Issue by jayanthchandra** [panoptes/panoptes-network#35]
Hi, 

Really appreciate the motives of the project. i looked into build [website]( www.panoptes-data.net) and noticed that i am not able to view any of the images. I have attached the screen grab here 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9390424/69005985-4c932700-094f-11ea-8960-3af983522968.gif)

Looking at the source, i noticed this is the cause for it. 
https://github.com/panoptes/panoptes-network/blob/f7be7f757d37613eb4749fee6ea5b77438dd5c98/observations-explorer/src/components/ObservationDetail.vue#L116

I have resolved the issue and have sent the PR for same. Do let me know your inputs.

**Comment by wtgee** [comment]
Thanks @jayanthchandra for seeing the issue and jumping in to fix it! I unfortunately haven't had a lot of time to put into this side of things. 

If you have ideas or features you'd like to see please let us know as we are looking to redo (or at least update) the data explorer.

**Comment by wtgee** [comment]
Closed by #36

**Comment by jayanthchandra** [comment]
> Thanks @jayanthchandra for seeing the issue and jumping in to fix it! I unfortunately haven't had a lot of time to put into this side of things.
> 
> If you have ideas or features you'd like to see please let us know as we are looking to redo (or at least update) the data explorer.

Sure, Have created few tasks/issues.  I get on free on weekends these days, if there is any changes/improvements, Can i pick that up ?
